name: auction_hub
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  provider: ^6.0.5
  flutter_local_notifications: ^17.2.2
  google_sign_in: ^6.2.1
  speech_to_text: ^6.6.0
  firebase_messaging: ^15.1.0
  firebase_messaging_web: ^3.8.13
  web: ^0.5.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  location: ^7.0.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  maps_launcher: ^2.2.1
  google_maps_flutter: ^2.9.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  flutter_polyline_points: ^2.1.0
  google_directions_api: ^0.10.0

  # Cupertino Icons for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0

flutter:

  # Ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
